### ISSUE TITLE
Rename fluff sprite to maia

### ISSUE THREAD

**Issue by adryd325** [kyrie25/spicetify-oneko#4]
The sprite named fluff was originally made by https://twitter.com/_Anunnery for maia on https://maia.crimew.gay/. I'm not sure if they want credit or anything but I figured I'd let you know

I'm happy my code was adapted to this, it means a lot that what i do can make others happy

**Comment by kyrie25** [comment]
Thanks for the heads up! I do in fact was acknowledged that the sprite was taken from the site sometime after it was compiled here and wanted to credit by adding it into the sprite name tooltip, but things happened and I kinda forgot about it until now 😅.

Also thank you, I'm honored to know that you like it as well!

**Comment by kyrie25** [comment]
Resolved via 5591a300c5c46f1287a96e9b4f3aba73c6840d7f.
