### ISSUE TITLE
[FEATURE REQUEST] Make sleeping the default behaviour when spotify is opened

### ISSUE THREAD

**Issue by andrewCohn** [kyrie25/spicetify-oneko#6]
This is more of a feature request than anything (if you can point me to the file, i'll gladly make the change myself!), but it would be nice to be able to make the neko either remember the if it was napping when I used spotify last or simply just nap by default. Thanks much.

**Comment by kyrie25** [comment]
Done! Check again in a few hours for Marketplace to update and see if it works as intended!
