### ISSUE TITLE
Issue with oneko ! 

### ISSUE THREAD

**Issue by parthchilwerwar** [kyrie25/spicetify-oneko#7]
![Screenshot 2024-07-02 120426](https://github.com/kyrie25/spicetify-oneko/assets/80417759/55ee2ea6-581b-4394-9625-16441d04b612)

You will get it through screenshot as my cursor is some where else and the cat is going some where idk whats the issue hope , many of like me are facing the same issue any solution that need to be made changes ?

**Comment by kyrie25** [comment]
Try putting the cat to sleep by double-clicking on it. Does it go to your trackbar or stops moving offscreen altogether?

If it stops moving, try putting the cat to sleep again. Does it keep run offscreen again?

**Comment by parthchilwerwar** [comment]
Thank for the reply , Now i tried to double click and now it following the cursor and more over idk what was happening exactly but i was facing lot of time ! but thanks to reslove it  
![image](https://github.com/kyrie25/spicetify-oneko/assets/80417759/a1fa259e-aed9-4b79-8f60-69884addbde0)
Now its following the cursor :) +1 and now its not running offscreen again

**Comment by kyrie25** [comment]
I can't replicate the problem and it seems that it has been resolved so I'll close this issue for now. Cheers!
