### ISSUE TITLE
Oneko has inverted color

### ISSUE THREAD

**Issue by thiccguy21** [kyrie25/spicetify-oneko#8]
Oneko's color seems inverted to me, I'vetried changing themes but the problem still persisted.
![image](https://github.com/user-attachments/assets/bcd5553f-c1e1-4e32-b61d-96e7491f699b)

**Comment by kyrie25** [comment]
This is a feature. Right click to re-invert the colors

https://github.com/kyrie25/spicetify-oneko/blob/589a8cc3a3939b8c9fc4f2bd087ed433e9af5002/README.md?plain=1#L23-L25
